### ISSUE TITLE
Delay Switch issue ?

### ISSUE THREAD

**Issue by Pblondin123** [nitaybz/homebridge-delay-switch#45]
Hi since approx 6pmEST 2021-02-19 seems that motion events are not going thru in Alexa (at least, my setup :-) ). Am not sure how to troubleshoot since the HB debug log is not giving me much.   Am running out of ideas on how to troubleshoot why my motion triggers are not happening. Fyi i upgraded to the latest Homebridge UI in the weekend not sure if this involves anything. tia.

**Comment by ucsbricks** [comment]
My setup updated yesterday to Homebridge 1.3.0 + Plugin 2.2.6 has the same issue w/ delay switches, while the Hue motion sensor connected through official Hue Alexa Skill still triggers Alexa routines.

I opened an issue in homebridge-alexa as I suspect the issue is related to this plugin:
https://github.com/NorthernMan54/homebridge-alexa/issues/421

**Comment by ucsbricks** [comment]
Please try to update homebridge-alexa to v0.5.30. This version fixed the issue for me.

**Comment by Pblondin123** [comment]
yes it fixed it thanks!
